export const MOBILE_CHANGED = 'MOBILE_CHANGED';
export const TOKEN_CHANGED = 'TOKEN_CHANGED';
export const USER_LOGIN_ATTEMP = 'USER_LOGIN_ATTEMP';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_GET_DATA='USER_GET_DATA';
